package com.haitun.bean;

// Generated 2016-2-3 11:57:06 by Hibernate Tools 4.0.0

/**
 * Booktags generated by hbm2java
 */
public class Booktags implements java.io.Serializable {

	private static final long serialVersionUID = -3845570737097728346L;
	private int id;
	private Category category;
	private Book book;

	public Booktags() {
	}

	public Booktags(Category category, Book book) {
		this.category = category;
		this.book = book;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

}
