package com.haitun.bean;

// Generated 2016-2-3 11:57:06 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.hibernate.annotations.Entity;
import org.springframework.stereotype.Component;

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	private static final long serialVersionUID = 8883338393691791595L;
	private String author;
	private Set booktagses=new HashSet(0);
	private Set comments=new HashSet(0);
	private String date;
	private List<String> categoryNames;
	
	private Integer id;

	private String image;
	private String isbn;
	private String name;
	private Integer page;
	private Float price;
	private String publisher;
	private String summary;
	private Integer reviewId;
	public Book() {
	}

	public Book(String name) {
		this.name = name;
	}

	public Book(String name, String isbn, String author, Float price,
			String date, String publisher, Integer page, String summary,
			String image, Set comments, Set booktagses) {
		this.name = name;
		this.isbn = isbn;
		this.author = author;
		this.price = price;
		this.date = date;
		this.publisher = publisher;
		this.page = page;
		this.summary = summary;
		this.image = image;
		this.comments = comments;
		this.booktagses = booktagses;
	}

	public String getAuthor() {
		return this.author;
	}

	public Set getBooktagses() {
		return this.booktagses;
	}

	public Set getComments() {
		return this.comments;
	}

	public String getDate() {
		return this.date;
	}

	public Integer getId() {
		return this.id;
	}

	public String getImage() {
		return this.image;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public String getName() {
		return this.name;
	}

	public Integer getPage() {
		return this.page;
	}

	public Float getPrice() {
		return this.price;
	}

	public String getPublisher() {
		return this.publisher;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public void setBooktagses(Set booktagses) {
		this.booktagses = booktagses;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setPage(Integer page) {
		this.page = page;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Override
	public String toString() {
		return "Book [id=" + id + ", name=" + name + ", isbn=" + isbn
				+ ", author=" + author + ", price=" + price + ", date=" + date
				+ ", publisher=" + publisher + ", page=" + page + ", summary="
				+ summary + ", image=" + image + "]";
	}

	public List<String> getCategoryNames() {
		return categoryNames;
	}

	public void setCategoryNames(List<String> categoryNames) {
		this.categoryNames = categoryNames;
	}

	public Integer getReviewId() {
		return reviewId;
	}

	public void setReviewId(Integer reviewId) {
		this.reviewId = reviewId;
	}

}
