package com.haitun.bean;

// Generated 2016-2-3 11:57:06 by Hibernate Tools 4.0.0

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;


/**
 * Borrow generated by hbm2java
 */
public class Borrow implements java.io.Serializable {

	
	private static final long serialVersionUID = -2221445509219511964L;
	private Integer id;
	private String studentId;
	private String bookName;
	@JSONField(format = "yyyy-MM-dd")
	private Date date;

	public Borrow() {
	}

	public Borrow(String studentId, String bookName, Date date) {
		this.studentId = studentId;
		this.bookName = bookName;
		this.date = date;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStudentId() {
		return this.studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
