package com.haitun.bean;


// Generated 2016-2-3 11:57:06 by Hibernate Tools 4.0.0

/**
 * User generated by hbm2java
 */

public class User implements java.io.Serializable {

	private static final long serialVersionUID = 2618223783189294403L;
	private String id;
	private String name;
	private String sex;
	private String major;
	private String grade;
	private float overdue;

	public User() {
	}

	public User(String id, String name, String sex) {
		this.id = id;
		this.name = name;
		this.sex = sex;
	}

	public User(String id, String name, String sex, String major, String grade,
			float overdue) {
		super();
		this.id = id;
		this.name = name;
		this.sex = sex;
		this.major = major;
		this.grade = grade;
		this.overdue = overdue;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public float getOverdue() {
		return overdue;
	}

	public void setOverdue(float overdue) {
		this.overdue = overdue;
	}

}
